// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jezilbyforbnopnjutkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplemlsYnlmb3Jibm9wbmp1dGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTI3ODgsImV4cCI6MjA3MjY2ODc4OH0._-NEDIjivtwpvOGTOa16gek25MPNd3qnucsAr8FnIaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});